### ISSUE TITLE
Would love to contact you

### ISSUE THREAD

**Issue by nimrodkra** [IgnusG/ignusg#1]
Hi Jonathan, it's Nimrod Kramer from daily.dev here :) I know it's not the most convenient way to reach out, but I'd love to have the chance to chat with you for a bit. Just have an idea that I'd be happy to share with you privately. I hope I'm not crossing any lines here lol 🙏

Would you mind sharing with me a way that I can content you? Alternatively, can you shoot me an email to nimrod at daily dot dev (We'll take it from there)?

**Comment by IgnusG** [comment]
Hi @nimrodkra! Thanks for your message and interest ❤️ 

I've sent you a reply to your email ;)
